version: '2'
services:
  db:
    image: postgres:9.6
    container_name: chat-app-db
    volumes:
      - chat_app_db:/var/lib/postgresql/db
    ports:
      - '5432:5432'

  redis:
    image: redis:3.0
    container_name: chat-app-redis
    ports:
      - '6379:6379'


volumes:
  chat_app_db:
