development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat-app_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat-app_production
